### ISSUE TITLE
Wrong braille translations?

### ISSUE THREAD

**Issue by JanPokorny** [AaditT/braille#1]
Some of the letters don't have correct translations in the 1/0 array (E, J, O, ...) -- are you using some non-standard form of Braille? This is the first Google result for "python braille library" and I was very surprised when it gave wrong results.

**Comment by treyharris** [comment]
Same—is there a more standard Braille library or an cross-platform bridge more appropriate to use? (Probably the demand isn’t great—because Braille is typically rendered via OS accessibility systems or even the Braille terminal driver—but for linguistics or teaching applications it would be helpful.)

**Comment by JanPokorny** [comment]
@treyharris I ended up just copying and fixing some code, since the whole thing is just a dict lookup. My use case was creating a puzzlehunt and needing to brute force possible answers to a puzzle -- which is probably a pretty rare usecase.

**Comment by AaditT** [comment]
Thanks for pointing this out, and apologies for any inconveniences this may have caused. I resolved the issue, and the translations are now accurate.
